
/**
 * Warning: This is an autogenerated file.
 *
 * Changes in this file won't take effect and will be overwritten
 */

// Base Types
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
type Maybe<T> = T | null | undefined
type Scalars = {
  Boolean: boolean
  String: string
  Float: number
  Int: number
  ID: string
}

// Operation related types
export type LandingPageQueryQueryVariables = Exact<{ [key: string]: never; }>;


export type LandingPageQueryQuery = { seo: Maybe<{ extraBlocks: Array<Maybe<{ blocks: Array<{ name: string, props: Maybe<any> }> }>> }>, content: Maybe<{ blocks: Array<Maybe<{ name: string, props: Maybe<any> }>> }> };


// Query Related Code

export const LandingPageQuery = {
  query: process.env.NODE_ENV === 'production' ? undefined : "query LandingPageQuery {\n  seo: vtexCmsPageContent(type: {eq: \"seo\"}) {\n    extraBlocks {\n      blocks {\n        name\n        props\n      }\n    }\n  }\n  content: vtexCmsPageContent(type: {eq: \"landingPage\"}) {\n    blocks {\n      name\n      props\n    }\n  }\n}\n",
  sha256Hash: "0c2bd7e06284654f4c3431abf7acd86369074138dc2389c765f6a054cd85a173",
  operationName: "LandingPageQuery",
}

