name: Lighthouse CI
on: pull_request
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: 'Wait for netlify deploy'
        run: |
          echo "Waiting for 120s so Netlify deploy is ready"
          sleep 180

      - name: Waiting for Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "faststore"
          max_timeout: 60

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          BASE_SITE_URL: ${{ steps.netlify.outputs.url }}
        with:
          serverBaseUrl: "http://lighthouse-ci.staging-2c.ingress.vtex.io/"
          serverToken: ${{ secrets.LHCI_TOKEN }}
          configPath: './lighthouserc.js'
          uploadArtifacts: true
